name: safeplus
description: "Student Safety & Support System - SafePulse App."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8

  # --- Firebase Services ---
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6  # මෙහි ඉහළ වර්ෂනය පාවිච්චි කිරීම වඩා සුදුසුයි

  # --- Maps & Location ---
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.2
  geocoding: ^4.0.0

  # --- Security & Alerts ---
  shake: ^3.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^20.1.0
  flutter_background_service: ^5.1.0
  record: ^6.2.0

  # --- Utilities ---
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  audioplayers: ^6.5.1
  record: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # --- App Icon එක සෑදීම සඳහා මෙය අවශ්‍යයි ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # --- සියලුම Assets ---
  assets:
    - assets/images/resource_sharing.png
    - assets/images/study_support.png
    - assets/images/safety_transport.png
    - assets/images/tech_support.png
    - assets/images/canteen_runner.png
    - assets/images/campus_logistics.png
    - assets/images/cash_exchange.png
    - assets/images/other.png
    - assets/images/sliit_map.png
    - assets/images/app_icon.png
    - assets/sounds/iphone_ringtone.mp3

# --- App Icon Settings ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
