// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlb4EmNOG4Zsd6hyO7qpdlZh708SLzEkw',
    appId: '1:852286665756:web:1e3c90ba9370e54307dbd9',
    messagingSenderId: '852286665756',
    projectId: 'safepluse-f4e9a',
    authDomain: 'safepluse-f4e9a.firebaseapp.com',
    storageBucket: 'safepluse-f4e9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDGarrel9GvUwdaXkiEIpX9DEkpn-lyU',
    appId: '1:852286665756:android:75ccb0c51f90474b07dbd9',
    messagingSenderId: '852286665756',
    projectId: 'safepluse-f4e9a',
    storageBucket: 'safepluse-f4e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArB7w8D9l56eFDj-j6rvSb2ln3JfLf-jk',
    appId: '1:852286665756:ios:5121f5af5bcf16fd07dbd9',
    messagingSenderId: '852286665756',
    projectId: 'safepluse-f4e9a',
    storageBucket: 'safepluse-f4e9a.firebasestorage.app',
    iosBundleId: 'com.example.safeplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArB7w8D9l56eFDj-j6rvSb2ln3JfLf-jk',
    appId: '1:852286665756:ios:5121f5af5bcf16fd07dbd9',
    messagingSenderId: '852286665756',
    projectId: 'safepluse-f4e9a',
    storageBucket: 'safepluse-f4e9a.firebasestorage.app',
    iosBundleId: 'com.example.safeplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlb4EmNOG4Zsd6hyO7qpdlZh708SLzEkw',
    appId: '1:852286665756:web:a35c44f96be89efb07dbd9',
    messagingSenderId: '852286665756',
    projectId: 'safepluse-f4e9a',
    authDomain: 'safepluse-f4e9a.firebaseapp.com',
    storageBucket: 'safepluse-f4e9a.firebasestorage.app',
  );

}